# Generated by Django 6.0.4 on 2026-04-15 08:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('description_detaillee', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('categorie', models.CharField(choices=[('STARTER', 'Entrée'), ('MAIN_COURSE', 'Plat Principal'), ('DESSERT', 'Dessert'), ('DRINK', 'Boisson')], default='MAIN_COURSE', max_length=50)),
                ('est_vegetarien', models.BooleanField(default=False)),
                ('indices_allergenes', models.CharField(blank=True, help_text='Ex: Gluten, Arachides', max_length=255)),
                ('est_disponible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('telephone_email', models.CharField(help_text='Coordonnées de contact', max_length=255)),
                ('date_heure', models.DateTimeField()),
                ('nombre_couverts', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('emplacement_prefere', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('CANCELLED', 'Annulée'), ('COMPLETED', 'Terminée')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaires_ouverture', models.JSONField(help_text="Format: {'Lundi': '09:00-22:00'}")),
                ('adresse_physique', models.TextField()),
                ('capacite_max', models.PositiveIntegerField()),
                ('politique_annulation', models.TextField()),
            ],
            options={
                'verbose_name': 'Information Restaurant',
                'verbose_name_plural': 'Informations Restaurant',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_etoiles', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_client', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.reservation')),
            ],
            options={
                'verbose_name': 'Avis Client',
                'ordering': ['-date_publication'],
            },
        ),
    ]
